version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: theme-ui
    versions:
    - 0.6.1
    - 0.6.2
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: "@theme-ui/components"
    versions:
    - 0.6.1
    - 0.6.2
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: react-content-loader
    versions:
    - 6.0.2
